import ReactQueryProviders from '@/utils/ReactQueryProviders'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from 'next/link'
// import "./globals.css";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <nav>
            <ul>
                <li>
                    <Link href="/">home</Link>
                </li>
                <li>
                    <Link href="/about">introduction</Link>
                </li>
                <li>
                    <Link href="/article">notice board</Link>
                </li>
                <li>
                    <Link href="/member/login">log in</Link>
                </li>
            </ul>
        </nav>
        <ReactQueryProviders>{children}</ReactQueryProviders>
        </body>
        </html>
    )
}
