services:
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: member
      MYSQL_USER: yu7i
      MYSQL_PASSWORD: 53cret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
