services:
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: member
      MYSQL_USER: yu7i
      MYSQL_PASSWORD: 53cret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.2

volumes:
  mariadb_data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
