spring:
  application.name: backend
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  docker:
    compose:
      enabled: false
custom:
  jwt:
    #    secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    secretKey: ======================HENDISANTIKA===========================
logging:
  level:
    root: INFO
    id.my.hendisantika.backend: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-doc

#logging:
#  level:
#    root: DEBUG
application-description: '@project.description@'
application-version: '@project.version@'
